spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION:86400000} # по дефолту 24 часа

keystore:
  path: ${KEYSTORE_PATH}
  password: ${KEYSTORE_PASSWORD}
  alias: ${KEYSTORE_ALIAS}

password:
  encoder:
    type: v2  # Возможные значения: v1, v2
