spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  mail:
    host: ${SPRING_MAIL_HOST}
    username: ${SPRING_MAIL_LOGIN_FROM}
    password: ${SPRING_MAIL_PASSWORD_FROM}
    port: ${SPRING_MAIL_PORT}
    protocol: ${SPRING_MAIL_PROTOCOL}
    connection-timeout: 10000  # Таймаут на подключение (10 секунд)
    timeout: 10000             # Таймаут на чтение данных (10 секунд)
    write-timeout: 10000       # Таймаут на запись данных (10 секунд)

mail:
  debug: ${MAIL_DEBUG:false}

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION:86400000} # по дефолту 24 часа

keystore:
  path: ${KEYSTORE_PATH}
  password: ${KEYSTORE_PASSWORD}
  alias: ${KEYSTORE_ALIAS}

password:
  encoder:
    type: v2  # Возможные значения: v1, v2
